spring:
  application:
    name: platform
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    username: platform_service
    password: service
    url: jdbc:postgresql://localhost:5432/platform